
USE LOKI;

CREATE TABLE EMPLOYEE(

	SNO INT,
	NAMEE VARCHAR(20),
	SALARY INT,
	HEIGHT FLOAT
    );

DROP TABLES EMPLOYEE;
CREATE TABLE EMPLOYEE(
ID INT,
NAMEE VARCHAR(30),
STREAM VARCHAR(20)
);

CREATE USER XYZ identified by '123';

GRANT SELECT,INSERT ON EMPLOYEE TO XYZ;
 INSERT INTO EMPLOYEE VALUES(9,"KING","AI");
 SHOW TABLES;
 SELECT * FROM EMPLOYEE;
 
 
REVOKE INSERT ON EMPLOYEE FROM XYZ;
 SELECT * FROM EMPLOYEE;
 create table customer(
   age int,
   namee varchar(30),
   phnNumber int
   );
   show tables;
   
   insert into customer values(22,"krishna",83415294),(22,"lokesh",123456);
   
   
   desc customer;
   ALTER TABLE CUSTOMER ADD COLUMN SNO INT;
   ALTER TABLE CUSTOMER DROP COLUMN AGE;
   SELECT * FROM CUSTOMER;
   INSERT INTO CUSTOMER VALUES(SNO=2);