USE CODEGNAN;
CREATE TABLE CUSTOMER(
NAMEE VARCHAR(20),
ID INT,
AMOUNT FLOAT
);
INSERT INTO CUSTOMER VALUES("LOKI",2009,300),("VANI",2010,1000);

CREATE TABLE EMPLOYEE(
SNO INT,
NAMEE VARCHAR(30),
SALARY INT,
HEIGHT float
);

ALTER TABLE EMPLOYEE
ADD COLUMN PHNNUMBER INT;
SHOW TABLES;

ALTER TABLE EMPLOYEE ADD( DEPART CHAR(3), PLACE VARCHAR(40),AGE INT);
ALTER TABLE EMPLOYEE DROP COLUMN HEIGHT;
ALTER TABLE EMPLOYEE MODIFY COLUMN NAMEE VARCHAR(90);
DESC EMPLOYEE;
INSERT INTO EMPLOYEE(SNO,NAMEE,SALARY) VALUES(2,"LOKI",100000);